=== AMZN-Gene/o3dcon-2022-multiplayer-workshop/MyMultiplayerGame/Gem/Code/Source/AutoGen/MultiplayerAutoComponentSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
<xs:element name="Component">
    <xs:complexType>
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                
                <!-- Component Relation -->
                <xs:element name="ComponentRelation" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="Constraint" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Incompatible" />
                                    <xs:enumeration value="Required" />
                                    <xs:enumeration value="Weak" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="HasController" type="xs:boolean" use="required"/>
                        <xs:attribute name="Name" type="xs:string" use="required"/>
                        <xs:attribute name="Namespace" type="xs:string" use="required"/>
                        <xs:attribute name="Include" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>

                <!-- Include Files -->
                <xs:element name="Include" minOccurs="0"  maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="File" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>

                <!-- Archetypes -->
                <xs:element name="ArchetypeProperty" minOccurs="0"  maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="Type" type="xs:string" use="required"/>
                        <xs:attribute name="Name" type="xs:string" use="required"/>
                        <xs:attribute name="Init" type="xs:string" use="required"/>
                        <xs:attribute name="Container" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Object" />
                                    <xs:enumeration value="Array" />
                                    <xs:enumeration value="Vector" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="Count" type="xs:string" use="optional" default="1"/> <!-- Using xs:string not xs:integer because the count may refer to a variable in code -->
                        <xs:attribute name="ExposeToEditor" type="xs:boolean" use="required"/>
                        <xs:attribute name="Description" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>

                <!-- Network Input -->
                <xs:element name="NetworkInput" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="Type" type="xs:string" use="required"/>
                        <xs:attribute name="Name" type="xs:string" use="required"/>
                        <xs:attribute name="Init" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>

                <!-- Network Property -->
                <xs:element name="NetworkProperty" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="Type" type="xs:string" use="required"/>
                        <xs:attribute name="Name" type="xs:string" use="required"/>
                        <xs:attribute name="Init" type="xs:string" use="required"/>
                        <!-- Valid Network Property ReplacateFrom->ReplicateTo Combinations: -->
                        <!--     1. Authority to Server -->
                        <!--     2. Authority to Autonomous -->
                        <!--     3. Authority to Client -->
                        <!--     4. Autonomous to Authority -->
                        <xs:attribute name="ReplicateFrom" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Authority" />
                                    <xs:enumeration value="Autonomous" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="ReplicateTo" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Authority" />
                                    <xs:enumeration value="Autonomous" />
                                    <xs:enumeration value="Client" />
                                    <xs:enumeration value="Server" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="Container" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Object" />
                                    <xs:enumeration value="Array" />
                                    <xs:enumeration value="Vector" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="Count" type="xs:string" use="optional" default="1"/> <!-- Using xs:string not xs:integer because the count may refer to a variable in code -->
                        <xs:attribute name="IsPublic" type="xs:boolean" use="required"/>
                        <xs:attribute name="IsRewindable" type="xs:boolean" use="required"/>
                        <xs:attribute name="IsPredictable" type="xs:boolean" use="required"/>
                        <xs:attribute name="ExposeToEditor" type="xs:boolean" use="required"/>
                        <xs:attribute name="ExposeToScript" type="xs:boolean" use="required"/>
                        <xs:attribute name="GenerateEventBindings" type="xs:boolean" use="required"/>
                        <xs:attribute name="Description" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>

                <!-- RPC -->
                <xs:element name="RemoteProcedure" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Param" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="Type" type="xs:string" use="required"/>
                                    <xs:attribute name="Name" type="xs:string" use="required"/>    
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>

                        <xs:attribute name="Name" type="xs:string" use="required"/>

                        <!-- Valid RPC InvokeFrom->HandleOn Combinations: -->
                        <!--     1. Authority to Autonomous -->
                        <!--     2. Authority to Client -->
                        <!--     3. Server to Authority -->
                        <!--     4. Autonomous to Authority -->
                        <xs:attribute name="InvokeFrom" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Authority" />
                                    <xs:enumeration value="Autonomous" />
                                    <xs:enumeration value="Server" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="HandleOn" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Authority" />
                                    <xs:enumeration value="Autonomous" />
                                    <xs:enumeration value="Client" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="IsPublic" type="xs:boolean" use="required"/>
                        <xs:attribute name="IsReliable" type="xs:boolean" use="required"/>
                        <xs:attribute name="GenerateEventBindings" type="xs:boolean" use="required"/>
                        <xs:attribute name="Description" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            
        </xs:sequence>

        <!-- Multiplayer Component Attributes -->
        <xs:attribute name="Name" type="xs:string" use="required"/>
        <xs:attribute name="Namespace" type="xs:string" use="required"/>
        <xs:attribute name="OverrideComponent" type="xs:boolean" use="required"/>
        <xs:attribute name="OverrideController" type="xs:boolean" use="required"/>
        <xs:attribute name="OverrideInclude" type="xs:string" use="required"/>
    </xs:complexType>
</xs:element>

</xs:schema>

=== AMZN-Gene/o3dcon-2022-multiplayer-workshop/MyMultiplayerGame/Gem/Code/Source/AutoGen/NetworkAnimationComponent.AutoComponent.xml
<?xml version="1.0"?>

<Component
    Name="NetworkAnimationComponent"
    Namespace="MyMultiplayerGame"
    OverrideComponent="true"
    OverrideController="false"
    OverrideInclude="Source/Components/NetworkAnimationComponent.h"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="MultiplayerAutoComponentSchema.xsd">

    <Include File="Source/MyMultiplayerGameTypes.h"/>

    <ComponentRelation Constraint="Required" HasController="true" Name="NetworkTransformComponent" Namespace="Multiplayer" Include="Multiplayer/Components/NetworkTransformComponent.h" />
    <ComponentRelation Constraint="Required" HasController="true" Name="NetworkSimplePlayerCameraComponent" Namespace="MyMultiplayerGame" Include="Source/Components/NetworkSimplePlayerCameraComponent.h" />
    <ComponentRelation Constraint="Weak" HasController="true" Name="NetworkPlayerMovementComponent" Namespace="MyMultiplayerGame" Include="Source/Components/NetworkPlayerMovementComponent.h" />

    <NetworkProperty Type="CharacterAnimStateBitset" Name="ActiveAnimStates" Init="false" ReplicateFrom="Authority" ReplicateTo="Client" IsRewindable="true" IsPredictable="true" IsPublic="true" Container="Object" ExposeToEditor="false" ExposeToScript="false" GenerateEventBindings="false" Description="Bitset of active animation states" />

    <ArchetypeProperty Type="AZStd::string" Name="VelocityParamName"  Init="" ExposeToEditor="true" Description="Anim graph velocity parameter"/>
    <ArchetypeProperty Type="AZStd::string" Name="AimTargetParamName" Init="" ExposeToEditor="true" Description="Anim graph aim target parameter"/>
    <ArchetypeProperty Type="AZStd::string" Name="CrouchParamName"    Init="" ExposeToEditor="true" Description="Anim graph crouch parameter"/>
    <ArchetypeProperty Type="AZStd::string" Name="AimingParamName"    Init="" ExposeToEditor="true" Description="Anim graph aiming parameter"/>
    <ArchetypeProperty Type="AZStd::string" Name="ShootParamName"     Init="" ExposeToEditor="true" Description="Anim graph shoot parameter"/>
    <ArchetypeProperty Type="AZStd::string" Name="JumpParamName"      Init="" ExposeToEditor="true" Description="Anim graph jump parameter"/>
    <ArchetypeProperty Type="AZStd::string" Name="FallParamName"      Init="" ExposeToEditor="true" Description="Anim graph fall parameter"/>
    <ArchetypeProperty Type="AZStd::string" Name="LandParamName"      Init="" ExposeToEditor="true" Description="Anim graph land parameter"/>
    <ArchetypeProperty Type="AZStd::string" Name="HitParamName"       Init="" ExposeToEditor="true" Description="Anim graph hit parameter"/>
    <ArchetypeProperty Type="AZStd::string" Name="DeathParamName"     Init="" ExposeToEditor="true" Description="Anim graph death parameter"/>
</Component>

=== AMZN-Gene/o3dcon-2022-multiplayer-workshop/MyMultiplayerGame/Gem/Code/Source/AutoGen/NetworkPlayerMovementComponent.AutoComponent.xml
<?xml version="1.0"?>

<Component
    Name="NetworkPlayerMovementComponent" 
    Namespace="MyMultiplayerGame" 
    OverrideComponent="false" 
    OverrideController="true" 
    OverrideInclude="Source/Components/NetworkPlayerMovementComponent.h"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="MultiplayerAutoComponentSchema.xsd">
    
    <ComponentRelation Constraint="Required" HasController="true" Name="NetworkTransformComponent" Namespace="Multiplayer" Include="Multiplayer/Components/NetworkTransformComponent.h" />
    <ComponentRelation Constraint="Required" HasController="true" Name="NetworkAnimationComponent" Namespace="MyMultiplayerGame" Include="Source/Components/NetworkAnimationComponent.h" />
    <ComponentRelation Constraint="Required" HasController="true" Name="NetworkCharacterComponent" Namespace="Multiplayer" Include="Multiplayer/Components/NetworkCharacterComponent.h" />
    <ComponentRelation Constraint="Required" HasController="true" Name="NetworkSimplePlayerCameraComponent" Namespace="MyMultiplayerGame" Include="Source/Components/NetworkSimplePlayerCameraComponent.h" />
    <ComponentRelation Constraint="Weak" HasController="true" Name="NetworkAiComponent" Namespace="MyMultiplayerGame" Include="Source/Components/NetworkAiComponent.h" />

    <Include File="Source/MyMultiplayerGameTypes.h"/>

    <NetworkProperty Type="AZ::Vector3" Name="Velocity" Init="AZ::Vector3::CreateZero()" ReplicateFrom="Authority" ReplicateTo="Client" IsRewindable="true" IsPredictable="true" IsPublic="true" Container="Object" ExposeToEditor="false" ExposeToScript="true" GenerateEventBindings="true" Description="Current velocity of this player"/>

    <NetworkInput Type="StickAxis" Name="ForwardAxis" Init="0.0f" />
    <NetworkInput Type="StickAxis" Name="StrafeAxis"  Init="0.0f" />
    <NetworkInput Type="MouseAxis" Name="ViewYaw"     Init="0.0f" />
    <NetworkInput Type="MouseAxis" Name="ViewPitch"   Init="0.0f" />
    <NetworkInput Type="bool"      Name="Sprint"      Init="false" />
    <NetworkInput Type="bool"      Name="Jump"        Init="false" />
    <NetworkInput Type="bool"      Name="Crouch"      Init="false" />
    <NetworkInput Type="uint8_t"   Name="ResetCount"  Init="0" />

    <ArchetypeProperty Type="float" Name="WalkSpeed"    Init="3.0f" ExposeToEditor="true" Description="Walk speed, units in meters per second" />
    <ArchetypeProperty Type="float" Name="SprintSpeed"  Init="5.0f" ExposeToEditor="true" Description="Sprint speed, units in meters per second" />
    <ArchetypeProperty Type="float" Name="ReverseSpeed" Init="2.0f" ExposeToEditor="true" Description="Reverse speed, units in meters per second" />
    <ArchetypeProperty Type="float" Name="CrouchSpeed"  Init="1.5f" ExposeToEditor="true" Description="Crouching speed, units in meters per second" />

</Component>
